//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.235
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Siage.UCControllers.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AgenteResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AgenteResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Siage.UCControllers.Resources.AgenteResource", typeof(AgenteResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ya existe un agente asociado a esa persona..
        /// </summary>
        internal static string AGENTE_EXISTE {
            get {
                return ResourceManager.GetString("AGENTE_EXISTE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El agente que esta intentando dar de baja, tiene asignaciones activas. Para poder dar de baja, primero debe dar de baja todas las asignaciones asociadas al agente..
        /// </summary>
        internal static string ASIGNACIONES_ACTIVAS {
            get {
                return ResourceManager.GetString("ASIGNACIONES_ACTIVAS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe ingresar el número de CUIL..
        /// </summary>
        internal static string CUIL_NULL {
            get {
                return ResourceManager.GetString("CUIL_NULL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe ingresar Tipo de documento y Número de documento..
        /// </summary>
        internal static string FILTRO_VACIO {
            get {
                return ResourceManager.GetString("FILTRO_VACIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe seleccionar una persona como agente..
        /// </summary>
        internal static string PERSONA_NULL {
            get {
                return ResourceManager.GetString("PERSONA_NULL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe seleccionar al menos un tipo de agente..
        /// </summary>
        internal static string TIPO_AGENTE_NULL {
            get {
                return ResourceManager.GetString("TIPO_AGENTE_NULL", resourceCulture);
            }
        }
    }
}
