//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Siage.UCControllers.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CargoMinimo {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CargoMinimo() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Siage.UCControllers.Resources.CargoMinimo", typeof(CargoMinimo).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El cargo mínimo ya existe.
        /// </summary>
        internal static string CargoMinimoExistente {
            get {
                return ResourceManager.GetString("CargoMinimoExistente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Falta configurar escuelas por tipo de nivel educativo. Consulte con el administrador del sistema..
        /// </summary>
        internal static string FaltaConfiguracionEscuelasPorTipoNivelEducativo {
            get {
                return ResourceManager.GetString("FaltaConfiguracionEscuelasPorTipoNivelEducativo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se puede reactivar un cargo mínimo en estado VIGENTE..
        /// </summary>
        internal static string ReactivarCargoVigente {
            get {
                return ResourceManager.GetString("ReactivarCargoVigente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El usuario actual no está configurado correctamente. Comuníquese con el administrador del sistema..
        /// </summary>
        internal static string SinAgenteAlta {
            get {
                return ResourceManager.GetString("SinAgenteAlta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categoría es un dato obligatorio..
        /// </summary>
        internal static string SinCategoria {
            get {
                return ResourceManager.GetString("SinCategoria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Faltan datos iniciales de la Dirección de Nivel logueada, consulte con su administrador..
        /// </summary>
        internal static string SinDN {
            get {
                return ResourceManager.GetString("SinDN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nivel Educativo es un dato obligatorio..
        /// </summary>
        internal static string SinNivelEducativo {
            get {
                return ResourceManager.GetString("SinNivelEducativo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo Cargo es un dato obligatorio..
        /// </summary>
        internal static string SinTipoCargo {
            get {
                return ResourceManager.GetString("SinTipoCargo", resourceCulture);
            }
        }
    }
}
