//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Siage.UCControllers.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CicloLectivoResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CicloLectivoResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Siage.UCControllers.Resources.CicloLectivoResource", typeof(CicloLectivoResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fechas erróneas en el calendario escolar..
        /// </summary>
        internal static string CalendarioFechasError {
            get {
                return ResourceManager.GetString("CalendarioFechasError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Existe el concepto en el calendario general..
        /// </summary>
        internal static string ExisteEnCalendario {
            get {
                return ResourceManager.GetString("ExisteEnCalendario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Existe el proceso o concepto en el calendario escolar..
        /// </summary>
        internal static string ExisteEnCalendarioEscolar {
            get {
                return ResourceManager.GetString("ExisteEnCalendarioEscolar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ciclo lectivo existente..
        /// </summary>
        internal static string Existente {
            get {
                return ResourceManager.GetString("Existente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La fecha de fin debe ser superior a la actual..
        /// </summary>
        internal static string FechaFinError {
            get {
                return ResourceManager.GetString("FechaFinError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La fecha de fin debe ser superior a la de inicio..
        /// </summary>
        internal static string FechasError {
            get {
                return ResourceManager.GetString("FechasError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Las fechas seleccionadas se encuentran fuera del período seleccinado..
        /// </summary>
        internal static string FechasPeriodo {
            get {
                return ResourceManager.GetString("FechasPeriodo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exiten fechas de inicio iguales en el calendario..
        /// </summary>
        internal static string FechasRepetidas {
            get {
                return ResourceManager.GetString("FechasRepetidas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Las fechas se encuentran fuera del período lectivo seleccionado..
        /// </summary>
        internal static string PeriodoError {
            get {
                return ResourceManager.GetString("PeriodoError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El proceso o etapa o el concepto son obligatorios..
        /// </summary>
        internal static string ProcesoConcepto {
            get {
                return ResourceManager.GetString("ProcesoConcepto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se deben cargar las fechas del calendario..
        /// </summary>
        internal static string SinDetalle {
            get {
                return ResourceManager.GetString("SinDetalle", resourceCulture);
            }
        }
    }
}
