//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Siage.UCControllers.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Contrato {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Contrato() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Siage.UCControllers.Resources.Contrato", typeof(Contrato).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Existe un contrato vigente para este tipo de bien..
        /// </summary>
        internal static string ExisteContratoVigente {
            get {
                return ResourceManager.GetString("ExisteContratoVigente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingrese las obsevaciones del tipo de adquisición y seleccione el motivo de baja..
        /// </summary>
        internal static string FaltanDatosDeBaja {
            get {
                return ResourceManager.GetString("FaltanDatosDeBaja", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Las fechas no son válidas..
        /// </summary>
        internal static string FechaInconsistente {
            get {
                return ResourceManager.GetString("FechaInconsistente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se puede guardar una persona física y jurídica..
        /// </summary>
        internal static string GuardarPersonaFisicaYJuridica {
            get {
                return ResourceManager.GetString("GuardarPersonaFisicaYJuridica", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se produjo un error al  consultar los contratos vencidos. Se debe configurar el valor del parámetro VENCIMIENTO_ALQUILER..
        /// </summary>
        internal static string PARAMETRO_VENC_ALQUILER_SIN_VALOR {
            get {
                return ResourceManager.GetString("PARAMETRO_VENC_ALQUILER_SIN_VALOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No existe un tipo de adquisición relacionada con este contrato.
        /// </summary>
        internal static string TipoAdquisicionRelacionadaInexistente {
            get {
                return ResourceManager.GetString("TipoAdquisicionRelacionadaInexistente", resourceCulture);
            }
        }
    }
}
