//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Siage.UCControllers.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class EdificioRules {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EdificioRules() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Siage.UCControllers.Resources.EdificioRules", typeof(EdificioRules).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe completar los datos de la casa habitación asociada..
        /// </summary>
        internal static string CASA_HABITACION {
            get {
                return ResourceManager.GetString("CASA_HABITACION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El edificio no puede ser eliminado porque tiene una casa habitación asociada..
        /// </summary>
        internal static string CASA_HABITACION_ASOCIADA {
            get {
                return ResourceManager.GetString("CASA_HABITACION_ASOCIADA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No existe un edificio con id={0}.
        /// </summary>
        internal static string EDIFICIO_ID_NO_EXISTENTE {
            get {
                return ResourceManager.GetString("EDIFICIO_ID_NO_EXISTENTE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El edificio debe tener al menos una planta..
        /// </summary>
        internal static string EDIFICIO_SIN_PLANTAS {
            get {
                return ResourceManager.GetString("EDIFICIO_SIN_PLANTAS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe ingresar una fecha de adquisición menor a la fecha actual..
        /// </summary>
        internal static string FECHA_ADQUISICION {
            get {
                return ResourceManager.GetString("FECHA_ADQUISICION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El valor ingresado en fecha de adquisición es invalido..
        /// </summary>
        internal static string FECHA_ADQUISICION_INVALIDA {
            get {
                return ResourceManager.GetString("FECHA_ADQUISICION_INVALIDA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cuando la función del edificio es &quot;Casa habitación&quot;  todos los locales asociados al mismo también deben ser &quot;Casa Habitación&quot;..
        /// </summary>
        internal static string LOCALES_CASA_HABITACION {
            get {
                return ResourceManager.GetString("LOCALES_CASA_HABITACION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe registrar al menos un local por planta. La siguiente planta no tiene local asociado..
        /// </summary>
        internal static string PLANTA_SIN_LOCAL {
            get {
                return ResourceManager.GetString("PLANTA_SIN_LOCAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe registrar al menos un local por planta. Las siguientes plantas no tienen locales asociados..
        /// </summary>
        internal static string PLANTA_SIN_LOCALES {
            get {
                return ResourceManager.GetString("PLANTA_SIN_LOCALES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe ingresar la altitud del edificio..
        /// </summary>
        internal static string SIN_ALTITUD {
            get {
                return ResourceManager.GetString("SIN_ALTITUD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe ingresar la altura del edificio..
        /// </summary>
        internal static string SIN_ALTURA {
            get {
                return ResourceManager.GetString("SIN_ALTURA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cuando la función del edificio es &quot;Casa habitación&quot; debe registrar los datos de la misma..
        /// </summary>
        internal static string SIN_CASA_HABITACION_EDIFICIO {
            get {
                return ResourceManager.GetString("SIN_CASA_HABITACION_EDIFICIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cuando alguno de los locales asociados al edificio es &quot;Casa habitación&quot; se deben registrar los datos de la misma..
        /// </summary>
        internal static string SIN_CASA_HABITACION_LOCAL {
            get {
                return ResourceManager.GetString("SIN_CASA_HABITACION_LOCAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe seleccionar el domicilio del edificio..
        /// </summary>
        internal static string SIN_DOMICILIO {
            get {
                return ResourceManager.GetString("SIN_DOMICILIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe seleccionar el estado del edificio..
        /// </summary>
        internal static string SIN_ESTADO {
            get {
                return ResourceManager.GetString("SIN_ESTADO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe seleccionar el tipo de estructura edilicia del edificio..
        /// </summary>
        internal static string SIN_ESTRUCTURA_EDIFILICIA {
            get {
                return ResourceManager.GetString("SIN_ESTRUCTURA_EDIFILICIA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe seleccionar la función del edifcio..
        /// </summary>
        internal static string SIN_FUNCION_EDIFICIO {
            get {
                return ResourceManager.GetString("SIN_FUNCION_EDIFICIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe ingresar la latituda del edificio..
        /// </summary>
        internal static string SIN_LATITUD {
            get {
                return ResourceManager.GetString("SIN_LATITUD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Al menos un local del Edificio debe ser casa habitación..
        /// </summary>
        internal static string SIN_LOCAL_CASA_HABITACION {
            get {
                return ResourceManager.GetString("SIN_LOCAL_CASA_HABITACION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El edificio tiene asociado una casa habitación, al menos un local debe ser casa habitación. Para dar de baja la casa habitación asociada, debe hacerlo desde la opción del menú: Gestionar Casa Habitación..
        /// </summary>
        internal static string SIN_LOCAL_CASA_HABITACION_EDICION {
            get {
                return ResourceManager.GetString("SIN_LOCAL_CASA_HABITACION_EDICION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe ingresar la longitud del edificio..
        /// </summary>
        internal static string SIN_LONGITUD {
            get {
                return ResourceManager.GetString("SIN_LONGITUD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe seleccionar un motivo de baja..
        /// </summary>
        internal static string SIN_MOTIVO_DE_BAJA {
            get {
                return ResourceManager.GetString("SIN_MOTIVO_DE_BAJA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe ingresar una observación..
        /// </summary>
        internal static string SIN_OBSERVACIONES {
            get {
                return ResourceManager.GetString("SIN_OBSERVACIONES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe adjuntar los archivos correspondientes a los planos del edificio..
        /// </summary>
        internal static string SIN_PLANOS {
            get {
                return ResourceManager.GetString("SIN_PLANOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe seleccionar un predio para registrar el edificio..
        /// </summary>
        internal static string SIN_PREDIO_SELECCIONADO {
            get {
                return ResourceManager.GetString("SIN_PREDIO_SELECCIONADO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe ingresar la referencia del edificio.
        /// </summary>
        internal static string SIN_REFERENCIA {
            get {
                return ResourceManager.GetString("SIN_REFERENCIA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe ingresar la superficie del edificio..
        /// </summary>
        internal static string SIN_SUPERFICIE {
            get {
                return ResourceManager.GetString("SIN_SUPERFICIE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe ingresar un tipo de adquisición..
        /// </summary>
        internal static string SIN_TIPO_ADQUISICION {
            get {
                return ResourceManager.GetString("SIN_TIPO_ADQUISICION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El edificio no puede ser eliminado porque tiene una empresa vinculada..
        /// </summary>
        internal static string TIENE_EMPRESA_ASOCIADA {
            get {
                return ResourceManager.GetString("TIENE_EMPRESA_ASOCIADA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El edificio no puede ser eliminado porque tiene un tipo de adquisición alquiler o comodato..
        /// </summary>
        internal static string TIPO_ADQUISICION_ASOCIADA {
            get {
                return ResourceManager.GetString("TIPO_ADQUISICION_ASOCIADA", resourceCulture);
            }
        }
    }
}
