//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Siage.UCControllers.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Empresa {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Empresa() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Siage.UCControllers.Resources.Empresa", typeof(Empresa).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Al menos un artículo en al resolución tiene datos incompletos.
        /// </summary>
        internal static string ArticuloIncompleto {
            get {
                return ResourceManager.GetString("ArticuloIncompleto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -10.
        /// </summary>
        internal static string ArtilugioParaDistinguirTipoInspeccionIntermediaEnumDeTipoInspeccionIntermediaObjeto {
            get {
                return ResourceManager.GetString("ArtilugioParaDistinguirTipoInspeccionIntermediaEnumDeTipoInspeccionIntermediaObje" +
                        "to", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activar Escuela.
        /// </summary>
        internal static string AsuntoMailActivarEmpresa {
            get {
                return ResourceManager.GetString("AsuntoMailActivarEmpresa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cerrar Empresa.
        /// </summary>
        internal static string AsuntoMailCerrarEmpresa {
            get {
                return ResourceManager.GetString("AsuntoMailCerrarEmpresa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reactivación de Empresa.
        /// </summary>
        internal static string AsuntoMailReactivarEmpresa {
            get {
                return ResourceManager.GetString("AsuntoMailReactivarEmpresa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La direccion de nivel del usuario logueado no tiene tipos de escuelas a crear.
        /// </summary>
        internal static string DireccionDeNivelSinTipoEscuelaACrear {
            get {
                return ResourceManager.GetString("DireccionDeNivelSinTipoEscuelaACrear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La empresa del usuario actual no es del tipo correcto.
        /// </summary>
        internal static string EmpresaActualIncorrecta {
            get {
                return ResourceManager.GetString("EmpresaActualIncorrecta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La empresa no existe.
        /// </summary>
        internal static string EmpresaNoExistente {
            get {
                return ResourceManager.GetString("EmpresaNoExistente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Código de empresa: formato no válido.
        /// </summary>
        internal static string ErrorFormatoCodigoEmpresa {
            get {
                return ResourceManager.GetString("ErrorFormatoCodigoEmpresa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ha ocurrido un error intentando registrar teléfono de la entidad. Comuníquese con el administrador del sistema.
        /// </summary>
        internal static string ErrorGuardandoTelefono {
            get {
                return ResourceManager.GetString("ErrorGuardandoTelefono", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La escuela es madre de otra escuela que no está cerrada..
        /// </summary>
        internal static string EscuelaMadre {
            get {
                return ResourceManager.GetString("EscuelaMadre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La escuela es raiz..
        /// </summary>
        internal static string EscuelaRaiz {
            get {
                return ResourceManager.GetString("EscuelaRaiz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to es dato requerido.
        /// </summary>
        internal static string EsDatoRequerido {
            get {
                return ResourceManager.GetString("EsDatoRequerido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La empresa no se encuentra en el estado correcto para realizar la operación..
        /// </summary>
        internal static string EstadoIncorrecto {
            get {
                return ResourceManager.GetString("EstadoIncorrecto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estructura escolar es dato requerido.
        /// </summary>
        internal static string EstructuraEscolarRequerida {
            get {
                return ResourceManager.GetString("EstructuraEscolarRequerida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5.
        /// </summary>
        internal static string IdTipoEscuelaEspecial {
            get {
                return ResourceManager.GetString("IdTipoEscuelaEspecial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El instrumento legal es requerido.
        /// </summary>
        internal static string InstrumentoLegalRequerido {
            get {
                return ResourceManager.GetString("InstrumentoLegalRequerido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe asociarse una escuela madre.
        /// </summary>
        internal static string NoSeAsocioEscuelaMadre {
            get {
                return ResourceManager.GetString("NoSeAsocioEscuelaMadre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe asociarse una escuela raíz.
        /// </summary>
        internal static string NoSeAsocioEscuelaRaiz {
            get {
                return ResourceManager.GetString("NoSeAsocioEscuelaRaiz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El número de instrumento legal ya se encuentra en uso.
        /// </summary>
        internal static string NumeroDeInstrumentoLegalExistente {
            get {
                return ResourceManager.GetString("NumeroDeInstrumentoLegalExistente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opción de envío no válida.
        /// </summary>
        internal static string OpcionEnvioNoValida {
            get {
                return ResourceManager.GetString("OpcionEnvioNoValida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La resolución tiene datos sin llenar.
        /// </summary>
        internal static string ResolucionIncompleta {
            get {
                return ResourceManager.GetString("ResolucionIncompleta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La resolución es dato requerido.
        /// </summary>
        internal static string ResolucionRequerida {
            get {
                return ResourceManager.GetString("ResolucionRequerida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La resolución debe tener al menos 1 artículo.
        /// </summary>
        internal static string ResolucionSinArticulos {
            get {
                return ResourceManager.GetString("ResolucionSinArticulos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Direccion de nivel del usuario actual no tiene inspecciones intermedias registradas.
        /// </summary>
        internal static string SinInspeccionesIntermedia {
            get {
                return ResourceManager.GetString("SinInspeccionesIntermedia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Los campos Tipo de educación y Nivel educativo son datos requeridos.
        /// </summary>
        internal static string SinNETE {
            get {
                return ResourceManager.GetString("SinNETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La empresa no cumple los requisitos para ser cerrada..
        /// </summary>
        internal static string SinRequisitos {
            get {
                return ResourceManager.GetString("SinRequisitos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teléfono no válido.
        /// </summary>
        internal static string TelefonoNoValido {
            get {
                return ResourceManager.GetString("TelefonoNoValido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El tipo de escuela no es válido.
        /// </summary>
        internal static string TipoEscuelaNoValido {
            get {
                return ResourceManager.GetString("TipoEscuelaNoValido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CIERRE EMPRESA.
        /// </summary>
        internal static string TipoInstrumentoLegalCierreEmpresa {
            get {
                return ResourceManager.GetString("TipoInstrumentoLegalCierreEmpresa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuario actual no tiene rol adecuado.
        /// </summary>
        internal static string UsuarioActualNoTieneRolAdecuado {
            get {
                return ResourceManager.GetString("UsuarioActualNoTieneRolAdecuado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OPZZ.
        /// </summary>
        internal static string ValorOrdenPagoCierreEmpresa {
            get {
                return ResourceManager.GetString("ValorOrdenPagoCierreEmpresa", resourceCulture);
            }
        }
    }
}
