//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Siage.UCControllers.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Inscripcion {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Inscripcion() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Siage.UCControllers.Resources.Inscripcion", typeof(Inscripcion).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El estudiante tiene una expulsión..
        /// </summary>
        internal static string ConExpulsion {
            get {
                return ResourceManager.GetString("ConExpulsion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cupo cubierto..
        /// </summary>
        internal static string Cupo {
            get {
                return ResourceManager.GetString("Cupo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Falta documentación obligatoria..
        /// </summary>
        internal static string DocumentacionObligatoria {
            get {
                return ResourceManager.GetString("DocumentacionObligatoria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se puede modificar la inscripción por su estado..
        /// </summary>
        internal static string EstadoModificacion {
            get {
                return ResourceManager.GetString("EstadoModificacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La fecha actual está fuera del período de inscripción habilitado por calendario escolar..
        /// </summary>
        internal static string FueraDeFecha {
            get {
                return ResourceManager.GetString("FueraDeFecha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El estudiante ya tiene una inscripción para el ciclo lectivo..
        /// </summary>
        internal static string Inscripto {
            get {
                return ResourceManager.GetString("Inscripto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El estudiante posee una inscripción con tipo de cursado normal para el ciclo lectivo..
        /// </summary>
        internal static string InscriptoCursadoNormal {
            get {
                return ResourceManager.GetString("InscriptoCursadoNormal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Falta datos a guardar..
        /// </summary>
        internal static string Modelo {
            get {
                return ResourceManager.GetString("Modelo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El estudiante no tiene una preinscripción..
        /// </summary>
        internal static string Preinscripcion {
            get {
                return ResourceManager.GetString("Preinscripcion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Situación académica incorrecta para registrar la inscripción..
        /// </summary>
        internal static string SituacionAcademica {
            get {
                return ResourceManager.GetString("SituacionAcademica", resourceCulture);
            }
        }
    }
}
