//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Siage.UCControllers.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LocalRules {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LocalRules() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Siage.UCControllers.Resources.LocalRules", typeof(LocalRules).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El local no puede ser dado de baja porque no existe otro local asociado a la casa habitación..
        /// </summary>
        internal static string LocalBajaCasaHabitacion {
            get {
                return ResourceManager.GetString("LocalBajaCasaHabitacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe ingresar un motivo para dar de baja el local..
        /// </summary>
        internal static string LocalBajaMotivo {
            get {
                return ResourceManager.GetString("LocalBajaMotivo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La cantidad de locales debe ser mayor o igual a 1..
        /// </summary>
        internal static string LocalCantidad {
            get {
                return ResourceManager.GetString("LocalCantidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El local debe ser casa habitación porque pertenece a un edificio que tiene como función casa habitación..
        /// </summary>
        internal static string LocalCasaHabitacion {
            get {
                return ResourceManager.GetString("LocalCasaHabitacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El local debe ser casa habitación. Al menos un local debe estar asociado a la casa habitación..
        /// </summary>
        internal static string LocalCasaHabitacionAsociado {
            get {
                return ResourceManager.GetString("LocalCasaHabitacionAsociado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El local no puede ser dado de baja porque no existe otro local asociado a la casa habitación..
        /// </summary>
        internal static string LocalCasaHabitacionBaja {
            get {
                return ResourceManager.GetString("LocalCasaHabitacionBaja", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Para un local en construcción debe ingresar el grado de avance y el plazo de la obra..
        /// </summary>
        internal static string LocalConstruccion {
            get {
                return ResourceManager.GetString("LocalConstruccion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ya existe un local registrado con el nombre y número de local ingresados..
        /// </summary>
        internal static string LocalExisteNombreNumero {
            get {
                return ResourceManager.GetString("LocalExisteNombreNumero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe ingresar el nombre del local..
        /// </summary>
        internal static string LocalNombre {
            get {
                return ResourceManager.GetString("LocalNombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe seleccionar el tipo de local..
        /// </summary>
        internal static string LocalTipoLocal {
            get {
                return ResourceManager.GetString("LocalTipoLocal", resourceCulture);
            }
        }
    }
}
