//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.235
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Siage.UCControllers.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Mab {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Mab() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Siage.UCControllers.Resources.Mab", typeof(Mab).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hay campos vacios.
        /// </summary>
        internal static string CamposVacios {
            get {
                return ResourceManager.GetString("CamposVacios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El o los codigos de movientos ya estan asignados a algun grupo.
        /// </summary>
        internal static string CodigoMovimientoAsignado {
            get {
                return ResourceManager.GetString("CodigoMovimientoAsignado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El código de movimiento Mab que se intenta desvincular, esta asignado a un MAB.
        /// </summary>
        internal static string CodigoMovimientoAsignadoMabEnDesvinculacion {
            get {
                return ResourceManager.GetString("CodigoMovimientoAsignadoMabEnDesvinculacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El codigo de movimiento ya existe..
        /// </summary>
        internal static string CodigoMovimientoExistente {
            get {
                return ResourceManager.GetString("CodigoMovimientoExistente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No ha seleccionado ningun codigo de movimiento MAB.
        /// </summary>
        internal static string GrupoSinCodigos {
            get {
                return ResourceManager.GetString("GrupoSinCodigos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El grupo seleccionado posee codigos de movimiento MAB asignados a un MAB, y este no puede ser eliminado.
        /// </summary>
        internal static string MabPoseeCodigosMovimientoAsignado {
            get {
                return ResourceManager.GetString("MabPoseeCodigosMovimientoAsignado", resourceCulture);
            }
        }
    }
}
