//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Siage.UCControllers.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Parametro {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Parametro() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Siage.UCControllers.Resources.Parametro", typeof(Parametro).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El valor que ha ingresado no corresponde a un número decimal válido..
        /// </summary>
        public static string DecimalMalFormato {
            get {
                return ResourceManager.GetString("DecimalMalFormato", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No es posible ingresar más de una dirección de correo electrónico.
        /// </summary>
        public static string EmailInvalido {
            get {
                return ResourceManager.GetString("EmailInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El formato de la dirección de correo electrónico ingresada es incorrecto.
        /// </summary>
        public static string EmailMalFormado {
            get {
                return ResourceManager.GetString("EmailMalFormado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El valor que ha ingresado no corresponde a un número entero válido..
        /// </summary>
        public static string EnteroMalFormato {
            get {
                return ResourceManager.GetString("EnteroMalFormato", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ya existe una valor para la fecha ingresada.
        /// </summary>
        public static string FechaVigenciaExistente {
            get {
                return ResourceManager.GetString("FechaVigenciaExistente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La fecha de inicio de vigencia debe ser mayor a la fecha actual.
        /// </summary>
        public static string FechaVigenciaInvalida {
            get {
                return ResourceManager.GetString("FechaVigenciaInvalida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se ha asignado una escuela a la regla de negocio.
        /// </summary>
        public static string RequiereEscuela {
            get {
                return ResourceManager.GetString("RequiereEscuela", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe seleccionar un valor para el parámetro.
        /// </summary>
        public static string ValorInvalido {
            get {
                return ResourceManager.GetString("ValorInvalido", resourceCulture);
            }
        }
    }
}
