//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Siage.UCControllers.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class PredioResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PredioResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Siage.UCControllers.Resources.PredioResource", typeof(PredioResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Las calles norte, sur, este, oeste no pueden ser iguales..
        /// </summary>
        internal static string CALLES_IGUALES {
            get {
                return ResourceManager.GetString("CALLES_IGUALES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contrato dado de baja por baja de parcela a través de la baja de predio..
        /// </summary>
        internal static string CONTRATO_BAJA {
            get {
                return ResourceManager.GetString("CONTRATO_BAJA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El predio no se puede dar de baja debido a que tiene un edificio vinculado activo..
        /// </summary>
        internal static string EDIFICIO_VINCULADO {
            get {
                return ResourceManager.GetString("EDIFICIO_VINCULADO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Existen 2 números de instrumento legal iguales, Para poder crear un instrumento legal que luego sera utilizado en 2 entidades distintas debe generarlo a través del acceso desde el menu &apos;Gestionar instrumento legal&apos;..
        /// </summary>
        internal static string INSTRUMENTO_LEGAL_IGUAL {
            get {
                return ResourceManager.GetString("INSTRUMENTO_LEGAL_IGUAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe seleccionar un motivo de alta..
        /// </summary>
        internal static string MOTIVO_ALTA {
            get {
                return ResourceManager.GetString("MOTIVO_ALTA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe ingresar un motivo de baja..
        /// </summary>
        internal static string MOTIVO_BAJA {
            get {
                return ResourceManager.GetString("MOTIVO_BAJA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El predio no podrá ser reactivado hasta que no se active todas o alguna/s de las parcela/s asociadas..
        /// </summary>
        internal static string PARCELAS_INACTIVAS {
            get {
                return ResourceManager.GetString("PARCELAS_INACTIVAS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El predio ya se encuentra activo..
        /// </summary>
        internal static string PREDIO_ACTIVO {
            get {
                return ResourceManager.GetString("PREDIO_ACTIVO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ya existe un predio con el mismo domicilio registrado..
        /// </summary>
        internal static string PREDIO_EXISTENTE {
            get {
                return ResourceManager.GetString("PREDIO_EXISTENTE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El predio se puede dar de baja debido a que tiene una o más parcelas con contrato de alquiler o comodato vigente..
        /// </summary>
        internal static string PREDIO_PARCELA_CONTRATO_VIGENTE {
            get {
                return ResourceManager.GetString("PREDIO_PARCELA_CONTRATO_VIGENTE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se deben seleccionar al menos dos predios para realizar una operación de unión..
        /// </summary>
        internal static string SIN_PREDIOS_SELECCIONADO_OPREACION_UNION {
            get {
                return ResourceManager.GetString("SIN_PREDIOS_SELECCIONADO_OPREACION_UNION", resourceCulture);
            }
        }
    }
}
