//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Siage.UCControllers.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TipoMovimientoInstrumentoLegalRulesResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TipoMovimientoInstrumentoLegalRulesResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Siage.UCControllers.Resources.TipoMovimientoInstrumentoLegalRulesResource", typeof(TipoMovimientoInstrumentoLegalRulesResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Existe una asignación de instrumento legal con este tipo de movimiento. No se pueden eliminar tipos de movimientos asociados con asignaciones de instrumento legal..
        /// </summary>
        internal static string EliminacionDeTipoMovConAsignacionRelacionada {
            get {
                return ResourceManager.GetString("EliminacionDeTipoMovConAsignacionRelacionada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se pueden eliminar los tipos de movimientos predefinidos..
        /// </summary>
        internal static string EliminacionDeTipoMovPredefinido {
            get {
                return ResourceManager.GetString("EliminacionDeTipoMovPredefinido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingrese un nombre para el tipo de movimiento..
        /// </summary>
        internal static string NombreRequerido {
            get {
                return ResourceManager.GetString("NombreRequerido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El nombre ingresado ya existe. Por favor, ingrese uno nuevo..
        /// </summary>
        internal static string NombreYaExistente {
            get {
                return ResourceManager.GetString("NombreYaExistente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se pueden reactivar tipos de movimientos predefinidos..
        /// </summary>
        internal static string ReactivacionDeTipoMovPredefinido {
            get {
                return ResourceManager.GetString("ReactivacionDeTipoMovPredefinido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se pueden registrar tipos de movimientos predefinidos..
        /// </summary>
        internal static string RegistracionDeTipoMovPredefinido {
            get {
                return ResourceManager.GetString("RegistracionDeTipoMovPredefinido", resourceCulture);
            }
        }
    }
}
