//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Siage.UCControllers.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TipoInspeccionIntermedia {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TipoInspeccionIntermedia() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Siage.UCControllers.Resources.TipoInspeccionIntermedia", typeof(TipoInspeccionIntermedia).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La empresa del usuario actual no es del tipo Direccion de Nivel.
        /// </summary>
        internal static string EmpresaIncorrecta {
            get {
                return ResourceManager.GetString("EmpresaIncorrecta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre repetido.
        /// </summary>
        internal static string NombreRepetido {
            get {
                return ResourceManager.GetString("NombreRepetido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El usuario actual no está configurado correctamente. Comuníquese con el administrador del sistema..
        /// </summary>
        internal static string SinAgenteAlta {
            get {
                return ResourceManager.GetString("SinAgenteAlta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre es dato requerido.
        /// </summary>
        internal static string SinNombre {
            get {
                return ResourceManager.GetString("SinNombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuario no logueado como direccion de nivel.
        /// </summary>
        internal static string UsuarioNoLogueadoComoDireccionDeNivel {
            get {
                return ResourceManager.GetString("UsuarioNoLogueadoComoDireccionDeNivel", resourceCulture);
            }
        }
    }
}
