//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Siage.UCControllers.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class VinculoEmpresaEdificioResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal VinculoEmpresaEdificioResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Siage.UCControllers.Resources.VinculoEmpresaEdificioResource", typeof(VinculoEmpresaEdificioResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe seleccionar al menos un edificio..
        /// </summary>
        internal static string EDIFICIO_NUL {
            get {
                return ResourceManager.GetString("EDIFICIO_NUL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe seleccionar una empresa..
        /// </summary>
        internal static string EMPRESA_NULL {
            get {
                return ResourceManager.GetString("EMPRESA_NULL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El vinculo no se puede dar de baja ya que el estado de la empresa no es &quot;Autorizado&quot; o &quot;En proceso de cierre autorizado/notificado&quot;. .
        /// </summary>
        internal static string ESTADO_EMPRESA {
            get {
                return ResourceManager.GetString("ESTADO_EMPRESA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe ingresar la fecha..
        /// </summary>
        internal static string FECHA_NULL {
            get {
                return ResourceManager.GetString("FECHA_NULL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El domicilio del edificio es el mismo que el domicilio de la empresa. Para poder dar de baja el vinculo, primero debe hacer el cambio de domicilio en edificio o empresa..
        /// </summary>
        internal static string MISMO_DOMICILIO {
            get {
                return ResourceManager.GetString("MISMO_DOMICILIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe seleccionar un motivo para poder dar de baja el vinculo..
        /// </summary>
        internal static string MOTIVO {
            get {
                return ResourceManager.GetString("MOTIVO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La empresa debe estar vinculada a un edificio para poder dar de baja el vinculo..
        /// </summary>
        internal static string VINCULO_NO_EXISTE {
            get {
                return ResourceManager.GetString("VINCULO_NO_EXISTE", resourceCulture);
            }
        }
    }
}
